#--------------------------
#	DATA PROPERTIES
#--------------------------
# DATASOURCE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-app
spring.datasource.username=postgres
spring.datasource.password=ajay
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082
# JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

 Shows the SQL queries and internal auth logic
logging.level.org.springframework.security=DEBUG
 Optional: See exact DB interactions
logging.level.org.springframework.jdbc=DEBUG

spring.security.user.name=
spring.security.user.password=
server.servlet.session.cookie.path-params=false